Add auth setup to notification command line script
The server /auth endpoint will now return comma-separated values
unless the client indicates json support so that it's easier to
populate .netrc in the shell script when setting up credentials via
the new -a flag.

This makes it easier to get set up with command-line notifications.

diff --git a/clients/send-notification b/clients/send-notification
--- a/clients/send-notification
+++ b/clients/send-notification
@@ -1,61 +1,125 @@
 #!/bin/sh
 
 #
-# A curl wrapper script for sending messages to notifier via the
-# command line.
+# Send messages to notifier from the command line via curl.
+#
+# Includes the ability to request a login token from a notifier and
+# save it to .netrc.
 #
 
-help() {
+set -u
+set -e
+
+usage() {
     cat <<EOF
-Usage: ${0##*/} -s SERVER  -t TITLE -g GROUP -b BODY -u URL -p PUSHBULLET_ID
 
-Send a message to notifier via curl populated with the given title,
-group, body, and url fields.
+This script sends a message populated with the specified fields to a
+notifier server via curl.
 
-Curl will look for a username and password in your .netrc file.
+If a server is not specified, the value of the NOTIFIER_SERVER
+environment variable will be used.
+
+To set up authentication:
+${0##*/} -a
+
+
+To sent a message once authenticated:
+${0##*/} -s SERVER -t TITLE -g GROUP -b BODY -u URL
+-p PUSHBULLET_ID
+
+
+To view this message:
+${0##*/} -h
 
 EOF
 }
 
-server=""
-title=""
-group=""
-body=""
-url=""
-pushbullet_id=""
+authorize() {
+    echo "Setting up access credentials."
+    
+    read -p "Enter the full URL of your notifier server: " NOTIFIER_URL
+
+    NOTIFIER_HOST_AND_PORT=${NOTIFIER_URL##*\/\/}
+    NOTIFIER_HOST=${NOTIFIER_HOST_AND_PORT%%:*}
+
+    read -p "Username: " NOTIFIER_USERNAME
+    read -s -p "Password: " NOTIFIER_PASSWORD
+
+    echo ""
+    echo ""
+
+    RESPONSE=$(curl -s \
+                    --write-out ",%{http_code}" \
+                    -d "username=$NOTIFIER_USERNAME" \
+                    -d "password=$NOTIFIER_PASSWORD" \
+                    -d "label=${0##*/}" \
+                    -d "persist=1" \
+                    $NOTIFIER_URL/auth)
+    
+    RESPONSE_CODE=${RESPONSE##*,}
+
+    if [ "$RESPONSE_CODE" != "200" ]; then
+        echo "Could not log in. Server returned $RESPONSE_CODE" >&2
+        exit;
+    fi
+    
+    RESPONSE_USER=$(echo "$RESPONSE" | cut -d "," -f 1)
+    RESPONSE_PASS=$(echo "$RESPONSE" | cut -d "," -f 2)
+
+    echo "machine $NOTIFIER_HOST login $RESPONSE_USER password $RESPONSE_PASS" >> $HOME/.netrc
+    echo "Credentials for $NOTIFIER_HOST have been saved in $HOME/.netrc"
+}
 
 OPTIND=1
-while getopts "hp:s:t:g:b:u:" opt; do
+SERVER="$NOTIFIER_SERVER"
+TITLE=""
+GROUP=""
+BODY=""
+URL=""
+PUSHBULLET_ID=""
+
+while getopts "ahp:s:t:g:b:u:" opt; do
     case "$opt" in
+        a)
+            authorize
+            exit
+            ;;
         s)
-            server="$OPTARG"
+            SERVER="$OPTARG"
             ;;
         t)
-            title="$OPTARG"
+            TITLE="$OPTARG"
             ;;
         g)
-            group="$OPTARG"
+            GROUP="$OPTARG"
             ;;
         b)
-            body="$OPTARG"
+            BODY="$OPTARG"
             ;;
         u)
-            url="$OPTARG"
+            URL="$OPTARG"
             ;;
         p)
-            pushbullet_id="$OPTARG"
+            PUSHBULLET_ID="$OPTARG"
             ;;
-        *)
-            help
-            exit 0
+        ?)
+            usage  >&2
+            exit 2
             ;;
     esac
 done
 shift "$((OPTIND-1))"
 
-if [ -z $server ]; then
-    help
-    exit 1
-fi
+if [ -z "$SERVER" ]; then
+    echo "ERROR: No server specified." >&2
+    echo "Run with -a flag to set up authentication credentials" >&2
+    exit 2
+fi    
 
-curl -s -n -d "title=$title" -d "group=$group" -d "body=$body" -d "url=$url" -d "pushbulletId=$pushbullet_id" "$server/message"
+curl -n -s \
+     -d "title=$TITLE" \
+     -d "group=$GROUP" \
+     -d "body=$BODY" \
+     -d "url=$URL"  \
+     -d "pushbulletId=$PUSHBULLET_ID" \
+     "$SERVER/message"
